### PR TITLE
Modernize, infer TypeScript types from selector

### PR DESCRIPTION
**Pull request by fregante**
- Streamline, modernize code
- In TypeScript 4.1, parse the selector to return the exact type
- Return `undefined` instead of `null`
- Use `for-of` internally, dropping IE11 support

### CODE REVIEW

**Comment by fregante** [comment]
This has been published as prerelease 7.0.0 on the `next` tag (it won't be installed by regular `npm install select-dom`)

**Comment by fregante** [comment]
Missing:

- [x] It needs to default to `HTMLElement` instead of `Element`; That likely means having to use `extends`/`infer` on the output of `ParseSelector`
- [x] Why are the type tests not failing? The all expect `HTMLElement` for no-tag selectors 🤔

**Comment by g-plane** [comment]
However, the original definition of `querySelector` from TypeScript is returning `Element`, not `HTMLElement`.

**Comment by fregante** [comment]
> However, the original definition of `querySelector` from TypeScript is returning `Element`, not `HTMLElement`.

Yeah, your module is correct, but `select` has always defaulted to `HTMLElement` because that's what the vast majority of elements are. It's just easier than having to specify `<HTMLElement>` every time, or in this case, `div.class`

**Comment by fregante** [comment]
I think now only missing:
- [x] https://github.com/g-plane/typed-query-selector/pull/10
- [x] https://github.com/g-plane/typed-query-selector/pull/9
- [x] Element generic support

**Pull request merged**
